overrides:
  '@babel/helpers@<7.26.10': '>=7.26.10'
  '@babel/runtime@<7.26.10': '>=7.26.10'
  axios@>=1.0.0 <1.12.0: '>=1.12.0'
  axios@>=1.0.0 <1.8.2: '>=1.8.2'
  axios@>=1.3.2 <=1.7.3: '>=1.7.4'
  body-parser@<1.20.3: '>=1.20.3'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  braces@<3.0.3: '>=3.0.3'
  cookie@<0.7.0: '>=0.7.0'
  cross-spawn@>=7.0.0 <7.0.5: '>=7.0.5'
  d3-color@<3.1.0: '>=3.1.0'
  esbuild@<=0.24.2: '>=0.25.0'
  express@<4.20.0: '>=4.20.0'
  form-data@<2.5.4: '>=2.5.4'
  form-data@>=3.0.0 <3.0.4: '>=3.0.4'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  get-func-name@<2.0.1: '>=2.0.1'
  markdown-to-jsx@<7.4.0: '>=7.4.0'
  micromatch@<4.0.8: '>=4.0.8'
  nanoid@<3.3.8: '>=3.3.8'
  on-headers@<1.1.0: '>=1.1.0'
  path-to-regexp@<0.1.10: '>=0.1.10'
  path-to-regexp@<0.1.12: '>=0.1.12'
  rollup@<2.79.2: '>=2.79.2'
  rollup@>=3.0.0 <3.29.5: '>=3.29.5'
  semver@<5.7.2: '>=5.7.2'
  semver@>=6.0.0 <6.3.1: '>=6.3.1'
  semver@>=7.0.0 <7.5.2: '>=7.5.2'
  send@<0.19.0: '>=0.19.0'
  serialize-javascript@>=6.0.0 <6.0.2: '>=6.0.2'
  serve-static@<1.16.0: '>=1.16.0'
  store2@<2.14.4: '>=2.14.4'
  tar-fs@>=2.0.0 <2.1.2: '>=2.1.2'
  tar-fs@>=2.0.0 <2.1.3: '>=2.1.3'
  tar@<6.2.1: '>=6.2.1'
  tmp@<=0.2.3: '>=0.2.4'
  vite@<4.5.10: '>=4.5.10'
  vite@<4.5.11: '>=4.5.11'
  vite@<4.5.12: '>=4.5.12'
  vite@<4.5.13: '>=4.5.13'
  vite@<=4.5.13: '>=4.5.14'
  vite@<=4.5.5: '>=4.5.6'
  vite@<=5.4.19: '>=5.4.20'
  vite@>=4.0.0 <4.5.4: '>=4.5.4'
  vite@>=4.0.0 <=4.5.3: '>=4.5.4'
  word-wrap@<1.2.4: '>=1.2.4'
  ws@>=6.0.0 <6.2.3: '>=6.2.3'
  ws@>=8.0.0 <8.17.1: '>=8.17.1'
