enum AvatarType {
  Vibrant = 'vibrant',
  Pumpkin = 'pumpkin',
  Heart = 'heart',
  Cerise = 'cerise',
  Nebula = 'nebula',
  Vanity = 'vanity',
  Gloomy = 'gloomy',
  Iris = 'iris',
  Gorgonzola = 'gorgonzola',
  Navy = 'navy',
  Rockman = 'rockman',
  Caribbean = 'caribbean',
  Lagoon = 'lagoon',
  Turquoise = 'turquoise',
  Hair = 'hair',
  Poisonous = 'poisonous',
  Lime = 'lime',
  Greyish = 'greyish',
}

export const avatarBgMap: Record<AvatarType, string> = {
  [AvatarType.Vibrant]: '#fab13c',
  [AvatarType.Pumpkin]: '#f67a1a',
  [AvatarType.Heart]: '#cc3e3e',
  [AvatarType.Cerise]: '#eb3673',
  [AvatarType.Nebula]: '#9121a3',
  [AvatarType.Vanity]: '#9c2ad6',
  [AvatarType.Gloomy]: '#855ee1',
  [AvatarType.Iris]: '#5350d1',
  [AvatarType.Gorgonzola]: '#3858da',
  [AvatarType.Navy]: '#1f7ce0',
  [AvatarType.Rockman]: '#3aa2f4',
  [AvatarType.Caribbean]: '#1cc3d9',
  [AvatarType.Lagoon]: '#1d96ae',
  [AvatarType.Turquoise]: '#1f9d8c',
  [AvatarType.Hair]: '#1eae66',
  [AvatarType.Poisonous]: '#33c333',
  [AvatarType.Lime]: '#80c026',
  [AvatarType.Greyish]: '#7f8697',
};
