name: Release Components to NPM
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: pnpm
        uses: pnpm/action-setup@v2
        with:
          cache: 'pnpm'
        run: pnpm install --no-frozen-lockfile && npx nx run react-components:build
      - name: Publish package on NPM 📦
        run: cd dist/react-components && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
