name: Build and Deploy
on:
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 16
      - name: Install and Build
        run: npm install && npx nx run react-components:build-storybook
      - name: Deploy To Github Pages
        run: npx -p @storybook/storybook-deployer storybook-to-ghpages --existing-output-dir=docs-build --branch gh-pages --source-branch main --ci true
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GH_TOKEN_ORG }}